# Application Configuration
app:
  name: "Case Management Backend"
  version: "1.0.0"

# Server Configuration
server:
  port: 8080
  gin_mode: "debug"  # Mode: "debug", "release"
  log_level: "info"  # Logging level: "debug", "info", "warn", "error"

# Database Configuration (PostgreSQL)
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "postgres"
  sslmode: "disable"

# Isilon Configuration
isilon:
  base_url: "localhost:9000"
  access_key: "ROOTNAME"
  secret_key: "CHANGEME123"
  bucket_name: "miniobucket"
  ssl: false

# External Services Configuration
services:
  agreement_api:
    base_url: "http://localhost:8001/api/v1"
