# Application Configuration
app:
  name: "Case Management Backend"
  version: "1.0.0"

# Server Configuration
server:
  port: 8080
  gin_mode: "debug"  # Mode: "debug", "release"
  log_level: "info"  # Logging level: "debug", "info", "warn", "error"

# Database Configuration (PostgreSQL)
database:
  host: "postgres.railway.internal"
  port: 5432
  user: "postgres"
  password: "eRVDZckmPOxaDqNvqGYFACorieIhXtVi"
  dbname: "railway"
  sslmode: "disable"
