# Application Configuration
app:
  name: "Template Go BFF"
  version: "1.0.0"

# Server Configuration
server:
  port: 8080
  gin_mode: "debug"  # Mode: "debug", "release"
  log_level: "info"  # Logging level: "debug", "info", "warn", "error"

# Database Configuration (PostgreSQL)
database:
  host: "10.251.1.103"
  port: 5432
  user: "bff"
  password: "Aeon*123"
  dbname: "case-management-backend-sit"
  sslmode: "disable"

ldap:
  host: "10.100.4.2"
  port: 389

# External Services Configuration
services:
  agreement_api:
    base_url: "http://localhost:8001/api/v1"

# Connector API
connector_api:
  base_url: "https://connectorapi.aeonth-sit.com"

# Header
headers:
  api_key: "IQARRf8ZhKChCN0ODn0BHQF4cBodzi7z"
  api_language: "EN"
  api_channel: "Case-Management"
  api_device_os: "Web"